import { PrismaClient } from '@prisma/client'

const prisma = new PrismaClient()

const cars = [
  // ─── Hatchbacks (10) ────────────────────────────────────────────────────────
  {
    make: 'Maruti Suzuki', model: 'Swift', variant: 'ZXi+',
    bodyType: 'hatchback', fuelType: 'petrol', transmission: 'manual',
    priceMinLakh: 6.49, priceMaxLakh: 9.64,
    mileageKmpl: 23.2, engineCc: 1197, powerBhp: 89.7, torqueNm: 113,
    seating: 5, safetyStars: null, bootLitres: 268, groundClearanceMm: 163,
    pros: JSON.stringify(['Best-in-class mileage', 'Peppy engine', 'Excellent resale value']),
    cons: JSON.stringify(['No NCAP rating', 'Rear legroom tight', 'Basic safety features']),
    bestFor: 'City commute, first-time buyers, mileage-conscious buyers',
  },
  {
    make: 'Maruti Suzuki', model: 'Baleno', variant: 'Alpha',
    bodyType: 'hatchback', fuelType: 'petrol', transmission: 'automatic',
    priceMinLakh: 6.61, priceMaxLakh: 9.88,
    mileageKmpl: 22.35, engineCc: 1197, powerBhp: 89.7, torqueNm: 113,
    seating: 5, safetyStars: null, bootLitres: 318, groundClearanceMm: 170,
    pros: JSON.stringify(['Largest boot in segment', 'Refined ride', 'Feature-rich']),
    cons: JSON.stringify(['No NCAP rating', 'Bland styling', 'CVT feels sluggish in city']),
    bestFor: 'Premium hatchback buyers, highway touring, feature seekers',
  },
  {
    make: 'Hyundai', model: 'i20', variant: 'Asta (O)',
    bodyType: 'hatchback', fuelType: 'petrol', transmission: 'automatic',
    priceMinLakh: 7.04, priceMaxLakh: 11.21,
    mileageKmpl: 20.35, engineCc: 1197, powerBhp: 88.5, torqueNm: 114,
    seating: 5, safetyStars: null, bootLitres: 311, groundClearanceMm: 172,
    pros: JSON.stringify(['Premium interiors', 'Sunroof available', 'Powerful turbo variant']),
    cons: JSON.stringify(['No NCAP rating', 'Expensive top variants', 'Turbo engine costly to maintain']),
    bestFor: 'Premium hatchback, young professionals, feature seekers',
  },
  {
    make: 'Tata', model: 'Tiago', variant: 'XZ+',
    bodyType: 'hatchback', fuelType: 'petrol', transmission: 'manual',
    priceMinLakh: 5.60, priceMaxLakh: 8.10,
    mileageKmpl: 19.8, engineCc: 1199, powerBhp: 86.0, torqueNm: 113,
    seating: 5, safetyStars: 4, bootLitres: 242, groundClearanceMm: 168,
    pros: JSON.stringify(['4-star NCAP safety', 'Value for money', 'Solid build quality']),
    cons: JSON.stringify(['Average mileage', 'Basic infotainment on lower trims', 'Rear legroom cramped']),
    bestFor: 'Safety-conscious first-time buyers, budget buyers',
  },
  {
    make: 'Tata', model: 'Altroz', variant: 'XZ+',
    bodyType: 'hatchback', fuelType: 'petrol', transmission: 'manual',
    priceMinLakh: 7.00, priceMaxLakh: 10.60,
    mileageKmpl: 19.08, engineCc: 1199, powerBhp: 86.0, torqueNm: 113,
    seating: 5, safetyStars: 5, bootLitres: 345, groundClearanceMm: 165,
    pros: JSON.stringify(['5-star NCAP — safest hatchback', 'Huge boot', 'Premium feel']),
    cons: JSON.stringify(['No automatic option', 'Turbo variant pricey', 'Heavy steering']),
    bestFor: 'Safety-first buyers, premium hatchback segment',
  },
  {
    make: 'Tata', model: 'Punch', variant: 'Accomplished',
    bodyType: 'hatchback', fuelType: 'petrol', transmission: 'automatic',
    priceMinLakh: 6.13, priceMaxLakh: 9.54,
    mileageKmpl: 18.82, engineCc: 1199, powerBhp: 86.0, torqueNm: 113,
    seating: 5, safetyStars: 5, bootLitres: 366, groundClearanceMm: 187,
    pros: JSON.stringify(['5-star NCAP', 'High ground clearance', 'SUV-like stance']),
    cons: JSON.stringify(['Smaller than compact SUVs', 'Average highway ride', 'Rear space limited']),
    bestFor: 'City SUV look on hatchback budget, safety-focused buyers',
  },
  {
    make: 'Maruti Suzuki', model: 'WagonR', variant: 'ZXI+',
    bodyType: 'hatchback', fuelType: 'cng', transmission: 'manual',
    priceMinLakh: 5.54, priceMaxLakh: 7.42,
    mileageKmpl: 34.05, engineCc: 1197, powerBhp: 76.9, torqueNm: 98.5,
    seating: 5, safetyStars: null, bootLitres: 341, groundClearanceMm: 170,
    pros: JSON.stringify(['Best running cost with CNG', 'Tall-boy spacious cabin', 'Excellent boot']),
    cons: JSON.stringify(['CNG reduces boot space', 'No NCAP rating', 'Slow performance']),
    bestFor: 'Daily commuters wanting ultra-low running costs, families needing space',
  },
  {
    make: 'Maruti Suzuki', model: 'Celerio', variant: 'ZXI',
    bodyType: 'hatchback', fuelType: 'petrol', transmission: 'automatic',
    priceMinLakh: 5.25, priceMaxLakh: 7.15,
    mileageKmpl: 26.68, engineCc: 998, powerBhp: 66.0, torqueNm: 89,
    seating: 5, safetyStars: null, bootLitres: 235, groundClearanceMm: 165,
    pros: JSON.stringify(['Highest mileage petrol automatic', 'Affordable AMT', 'Light to drive']),
    cons: JSON.stringify(['Underpowered on highways', 'Basic interiors', 'No safety rating']),
    bestFor: 'Budget automatic buyers, stop-go city traffic',
  },
  {
    make: 'Hyundai', model: 'Grand i10 Nios', variant: 'Magna',
    bodyType: 'hatchback', fuelType: 'petrol', transmission: 'manual',
    priceMinLakh: 5.92, priceMaxLakh: 8.60,
    mileageKmpl: 20.7, engineCc: 1197, powerBhp: 82.85, torqueNm: 114,
    seating: 5, safetyStars: null, bootLitres: 260, groundClearanceMm: 165,
    pros: JSON.stringify(['Sporty looks', 'Comfortable ride', 'Good features']),
    cons: JSON.stringify(['No NCAP rating', 'Rear space tight', 'Turbo variant expensive']),
    bestFor: 'Sporty hatchback look, city driving',
  },
  {
    make: 'Toyota', model: 'Glanza', variant: 'V',
    bodyType: 'hatchback', fuelType: 'petrol', transmission: 'automatic',
    priceMinLakh: 6.73, priceMaxLakh: 9.69,
    mileageKmpl: 22.35, engineCc: 1197, powerBhp: 89.7, torqueNm: 113,
    seating: 5, safetyStars: null, bootLitres: 318, groundClearanceMm: 170,
    pros: JSON.stringify(['Toyota reliability brand', 'Low service cost', 'Good resale value']),
    cons: JSON.stringify(['Rebadged Baleno', 'No NCAP rating', 'Limited service centres']),
    bestFor: 'Toyota brand trust seekers, reliability-focused buyers',
  },

  // ─── Sedans (8) ─────────────────────────────────────────────────────────────
  {
    make: 'Honda', model: 'City', variant: 'ZX CVT',
    bodyType: 'sedan', fuelType: 'petrol', transmission: 'cvt',
    priceMinLakh: 11.49, priceMaxLakh: 15.73,
    mileageKmpl: 18.8, engineCc: 1498, powerBhp: 121.0, torqueNm: 145,
    seating: 5, safetyStars: 2, bootLitres: 506, groundClearanceMm: 165,
    pros: JSON.stringify(['Spacious rear cabin', 'Refined CVT', 'Huge 506L boot']),
    cons: JSON.stringify(['Only 2-star NCAP', 'Expensive compared to SUVs', 'Diesel discontinued']),
    bestFor: 'Chauffeur-driven use, highway comfort, executive buyers',
  },
  {
    make: 'Hyundai', model: 'Verna', variant: 'SX(O) Turbo',
    bodyType: 'sedan', fuelType: 'petrol', transmission: 'automatic',
    priceMinLakh: 10.90, priceMaxLakh: 17.99,
    mileageKmpl: 20.0, engineCc: 1497, powerBhp: 158.0, torqueNm: 253,
    seating: 5, safetyStars: null, bootLitres: 528, groundClearanceMm: 165,
    pros: JSON.stringify(['Most powerful in segment', 'Premium interiors', 'Feature-loaded']),
    cons: JSON.stringify(['Expensive top trim', 'No NCAP rating yet', 'Turbo needs premium fuel']),
    bestFor: 'Performance sedan buyers, feature-focused executives',
  },
  {
    make: 'Maruti Suzuki', model: 'Dzire', variant: 'ZXI+',
    bodyType: 'sedan', fuelType: 'petrol', transmission: 'automatic',
    priceMinLakh: 6.79, priceMaxLakh: 9.64,
    mileageKmpl: 23.26, engineCc: 1197, powerBhp: 89.7, torqueNm: 113,
    seating: 5, safetyStars: null, bootLitres: 378, groundClearanceMm: 163,
    pros: JSON.stringify(['Best-selling sedan', 'Excellent mileage', 'Best resale value']),
    cons: JSON.stringify(['No NCAP rating', 'Underpowered engine', 'Basic safety features']),
    bestFor: 'Cab/fleet operators, value sedan buyers, mileage seekers',
  },
  {
    make: 'Tata', model: 'Tigor', variant: 'XZ+',
    bodyType: 'sedan', fuelType: 'petrol', transmission: 'manual',
    priceMinLakh: 6.30, priceMaxLakh: 8.89,
    mileageKmpl: 19.93, engineCc: 1199, powerBhp: 86.0, torqueNm: 113,
    seating: 5, safetyStars: 4, bootLitres: 419, groundClearanceMm: 165,
    pros: JSON.stringify(['4-star NCAP safety', 'Value pricing', 'Generous boot']),
    cons: JSON.stringify(['Plain interiors', 'No automatic below top trim', 'Underpowered']),
    bestFor: 'Budget sedan with safety, first sedan buyers',
  },
  {
    make: 'Honda', model: 'Amaze', variant: 'VX CVT',
    bodyType: 'sedan', fuelType: 'petrol', transmission: 'cvt',
    priceMinLakh: 7.20, priceMaxLakh: 10.60,
    mileageKmpl: 18.6, engineCc: 1198, powerBhp: 90.0, torqueNm: 110,
    seating: 5, safetyStars: null, bootLitres: 420, groundClearanceMm: 165,
    pros: JSON.stringify(['Compact size easy to park', 'Smooth CVT', 'Good boot space']),
    cons: JSON.stringify(['No NCAP rating', 'Feels underpowered', 'Dated interior']),
    bestFor: 'Compact sedan for narrow city streets',
  },
  {
    make: 'Skoda', model: 'Slavia', variant: 'Style 1.5 TSI',
    bodyType: 'sedan', fuelType: 'petrol', transmission: 'automatic',
    priceMinLakh: 13.69, priceMaxLakh: 19.99,
    mileageKmpl: 19.81, engineCc: 1498, powerBhp: 148.0, torqueNm: 250,
    seating: 5, safetyStars: null, bootLitres: 521, groundClearanceMm: 179,
    pros: JSON.stringify(['European build quality', 'Powerful turbo', 'Huge boot']),
    cons: JSON.stringify(['Expensive', 'High maintenance cost', 'Service network smaller']),
    bestFor: 'Premium performance sedan buyers, driving enthusiasts',
  },
  {
    make: 'Volkswagen', model: 'Virtus', variant: 'GT Plus 1.5 TSI',
    bodyType: 'sedan', fuelType: 'petrol', transmission: 'automatic',
    priceMinLakh: 12.99, priceMaxLakh: 19.33,
    mileageKmpl: 19.89, engineCc: 1498, powerBhp: 148.0, torqueNm: 250,
    seating: 5, safetyStars: null, bootLitres: 521, groundClearanceMm: 179,
    pros: JSON.stringify(['German build quality', '150 bhp hot sedan', 'Smooth DSG gearbox']),
    cons: JSON.stringify(['Expensive', 'Limited service network', 'DSG costly to service']),
    bestFor: 'Driving enthusiasts, premium sedan segment',
  },
  {
    make: 'Hyundai', model: 'Aura', variant: 'SX+',
    bodyType: 'sedan', fuelType: 'cng', transmission: 'manual',
    priceMinLakh: 6.58, priceMaxLakh: 9.89,
    mileageKmpl: 28.4, engineCc: 1197, powerBhp: 68.05, torqueNm: 95.2,
    seating: 5, safetyStars: null, bootLitres: 402, groundClearanceMm: 165,
    pros: JSON.stringify(['Best CNG mileage in sedan', 'Factory-fitted CNG reliable', 'Good features']),
    cons: JSON.stringify(['CNG hurts performance', 'No NCAP rating', 'Reduced boot with CNG']),
    bestFor: 'Fleet buyers, long-distance daily commuters wanting low running cost',
  },

  // ─── Compact SUVs (12) ───────────────────────────────────────────────────────
  {
    make: 'Tata', model: 'Nexon', variant: 'XZ+ (S)',
    bodyType: 'suv', fuelType: 'petrol', transmission: 'automatic',
    priceMinLakh: 8.10, priceMaxLakh: 15.50,
    mileageKmpl: 17.01, engineCc: 1199, powerBhp: 120.0, torqueNm: 170,
    seating: 5, safetyStars: 5, bootLitres: 350, groundClearanceMm: 209,
    pros: JSON.stringify(['5-star NCAP — safest compact SUV', 'High ground clearance', 'Powerful turbo']),
    cons: JSON.stringify(['Smaller cabin than rivals', 'Rear seat slightly upright', 'AMT jerky at low speeds']),
    bestFor: 'Safety-first families, city + weekend highway use',
  },
  {
    make: 'Maruti Suzuki', model: 'Brezza', variant: 'ZXI+ AT',
    bodyType: 'suv', fuelType: 'petrol', transmission: 'automatic',
    priceMinLakh: 8.34, priceMaxLakh: 14.29,
    mileageKmpl: 19.89, engineCc: 1462, powerBhp: 103.0, torqueNm: 137,
    seating: 5, safetyStars: null, bootLitres: 328, groundClearanceMm: 198,
    pros: JSON.stringify(['Best mileage in compact SUV segment', 'Excellent resale value', 'Strong Maruti service network']),
    cons: JSON.stringify(['No NCAP rating', 'Underpowered vs turbo rivals', 'Premium feels plasticky']),
    bestFor: 'Mileage-focused SUV buyers, Maruti service network priority',
  },
  {
    make: 'Hyundai', model: 'Creta', variant: 'SX Executive',
    bodyType: 'suv', fuelType: 'petrol', transmission: 'automatic',
    priceMinLakh: 11.19, priceMaxLakh: 20.45,
    mileageKmpl: 17.4, engineCc: 1497, powerBhp: 113.4, torqueNm: 144,
    seating: 5, safetyStars: 3, bootLitres: 433, groundClearanceMm: 190,
    pros: JSON.stringify(['Premium cabin quality', '3-star NCAP', 'Strong resale value']),
    cons: JSON.stringify(['Expensive top variants', 'Base petrol underpowered', 'Firm ride on bad roads']),
    bestFor: 'Families wanting premium SUV, highway cruising, strong resale',
  },
  {
    make: 'Kia', model: 'Sonet', variant: 'HTX+ Turbo DCT',
    bodyType: 'suv', fuelType: 'petrol', transmission: 'dct',
    priceMinLakh: 8.99, priceMaxLakh: 15.80,
    mileageKmpl: 18.3, engineCc: 998, powerBhp: 118.36, torqueNm: 172,
    seating: 5, safetyStars: null, bootLitres: 385, groundClearanceMm: 211,
    pros: JSON.stringify(['Feature-loaded at price', 'Punchy turbo petrol', 'Best-in-class ground clearance']),
    cons: JSON.stringify(['No NCAP rating', 'DCT not ideal for bumper-to-bumper traffic', 'Tight rear headroom']),
    bestFor: 'Feature seekers on budget, weekend adventurers, young families',
  },
  {
    make: 'Hyundai', model: 'Venue', variant: 'SX(O) Turbo DCT',
    bodyType: 'suv', fuelType: 'petrol', transmission: 'dct',
    priceMinLakh: 7.94, priceMaxLakh: 13.94,
    mileageKmpl: 18.45, engineCc: 998, powerBhp: 118.36, torqueNm: 172,
    seating: 5, safetyStars: null, bootLitres: 350, groundClearanceMm: 195,
    pros: JSON.stringify(['Connected car features', 'Punchy turbo', 'Compact for city parking']),
    cons: JSON.stringify(['No NCAP rating', 'Smaller than Creta', 'Rear space tight']),
    bestFor: 'Young urban buyers, connected car features, compact city SUV',
  },
  {
    make: 'Volkswagen', model: 'Taigun', variant: 'GT Plus 1.5 TSI DSG',
    bodyType: 'suv', fuelType: 'petrol', transmission: 'automatic',
    priceMinLakh: 12.69, priceMaxLakh: 19.33,
    mileageKmpl: 17.77, engineCc: 1498, powerBhp: 148.0, torqueNm: 250,
    seating: 5, safetyStars: 5, bootLitres: 385, groundClearanceMm: 188,
    pros: JSON.stringify(['5-star NCAP', '150 bhp — fastest compact SUV', 'German build quality']),
    cons: JSON.stringify(['Expensive', 'Limited service network', 'DSG service cost high']),
    bestFor: 'Driving enthusiasts wanting compact SUV + performance + safety',
  },
  {
    make: 'Skoda', model: 'Kushaq', variant: 'Style 1.5 TSI AT',
    bodyType: 'suv', fuelType: 'petrol', transmission: 'automatic',
    priceMinLakh: 12.49, priceMaxLakh: 18.89,
    mileageKmpl: 17.77, engineCc: 1498, powerBhp: 148.0, torqueNm: 250,
    seating: 5, safetyStars: null, bootLitres: 385, groundClearanceMm: 188,
    pros: JSON.stringify(['European build quality', 'Powerful 1.5 turbo', 'Comfortable ride']),
    cons: JSON.stringify(['Expensive', 'Limited dealerships', 'High maintenance']),
    bestFor: 'Premium European feel compact SUV buyers',
  },
  {
    make: 'Nissan', model: 'Magnite', variant: 'XV Premium Turbo CVT',
    bodyType: 'suv', fuelType: 'petrol', transmission: 'cvt',
    priceMinLakh: 6.60, priceMaxLakh: 11.60,
    mileageKmpl: 17.75, engineCc: 999, powerBhp: 99.0, torqueNm: 160,
    seating: 5, safetyStars: null, bootLitres: 336, groundClearanceMm: 205,
    pros: JSON.stringify(['Most affordable compact SUV', 'Good feature-to-price ratio', 'Panoramic sunroof at price']),
    cons: JSON.stringify(['No NCAP rating', 'Smaller service network', 'Feels budget inside']),
    bestFor: 'Entry-level compact SUV buyers, budget-first choosers',
  },
  {
    make: 'Renault', model: 'Kiger', variant: 'RXZ Turbo CVT',
    bodyType: 'suv', fuelType: 'petrol', transmission: 'cvt',
    priceMinLakh: 6.49, priceMaxLakh: 11.49,
    mileageKmpl: 18.2, engineCc: 999, powerBhp: 99.0, torqueNm: 160,
    seating: 5, safetyStars: null, bootLitres: 405, groundClearanceMm: 205,
    pros: JSON.stringify(['Largest boot in entry compact SUV', 'High ground clearance', 'Affordable pricing']),
    cons: JSON.stringify(['No NCAP rating', 'Small Renault service network', 'Interior quality basic']),
    bestFor: 'Tight budget compact SUV, boot space priority',
  },
  {
    make: 'Mahindra', model: 'XUV300', variant: 'W8 (O) Turbo',
    bodyType: 'suv', fuelType: 'petrol', transmission: 'manual',
    priceMinLakh: 8.61, priceMaxLakh: 14.49,
    mileageKmpl: 17.0, engineCc: 1197, powerBhp: 110.0, torqueNm: 200,
    seating: 5, safetyStars: 5, bootLitres: 257, groundClearanceMm: 180,
    pros: JSON.stringify(['5-star Global NCAP', 'Highest torque in class', 'Sunroof + disc brakes all round']),
    cons: JSON.stringify(['Smallest boot in segment', 'No automatic available', 'Limited variants']),
    bestFor: 'Safety-focused buyers, torque and grunt seekers',
  },
  {
    make: 'Toyota', model: 'Urban Cruiser Hyryder', variant: 'S Hybrid',
    bodyType: 'suv', fuelType: 'hybrid', transmission: 'automatic',
    priceMinLakh: 15.00, priceMaxLakh: 19.49,
    mileageKmpl: 27.97, engineCc: 1490, powerBhp: 91.6, torqueNm: 122,
    seating: 5, safetyStars: null, bootLitres: 328, groundClearanceMm: 200,
    pros: JSON.stringify(['Best mileage in SUV segment', 'Strong Hybrid — no charging needed', 'Ultra-low running cost']),
    cons: JSON.stringify(['Expensive upfront', 'No manual option', 'Less powerful than turbo rivals']),
    bestFor: 'High-mileage drivers, eco-conscious buyers, Bengaluru/Mumbai highway commuters',
  },
  {
    make: 'Maruti Suzuki', model: 'Grand Vitara', variant: 'Alpha+ Hybrid',
    bodyType: 'suv', fuelType: 'hybrid', transmission: 'automatic',
    priceMinLakh: 11.58, priceMaxLakh: 20.29,
    mileageKmpl: 27.97, engineCc: 1490, powerBhp: 91.6, torqueNm: 122,
    seating: 5, safetyStars: null, bootLitres: 373, groundClearanceMm: 210,
    pros: JSON.stringify(['Best mileage + highest ground clearance', 'Maruti service everywhere', 'Strong hybrid']),
    cons: JSON.stringify(['No NCAP rating', 'Hybrid expensive to repair', 'Hybrid system complex']),
    bestFor: 'Long-distance commuters, eco buyers with Maruti service priority',
  },

  // ─── Mid SUVs (8) ────────────────────────────────────────────────────────────
  {
    make: 'Kia', model: 'Seltos', variant: 'HTX Plus Turbo DCT',
    bodyType: 'suv', fuelType: 'petrol', transmission: 'dct',
    priceMinLakh: 14.56, priceMaxLakh: 21.12,
    mileageKmpl: 16.5, engineCc: 1497, powerBhp: 158.0, torqueNm: 253,
    seating: 5, safetyStars: null, bootLitres: 433, groundClearanceMm: 190,
    pros: JSON.stringify(['Premium 10.25" connected screen', 'Powerful turbo', 'Upscale cabin']),
    cons: JSON.stringify(['No NCAP rating', 'DCT needs careful city driving', 'Expensive top trims']),
    bestFor: 'Premium mid-SUV buyers wanting tech + power',
  },
  {
    make: 'Mahindra', model: 'XUV700', variant: 'AX7 L Turbo AT 5-seater',
    bodyType: 'suv', fuelType: 'petrol', transmission: 'automatic',
    priceMinLakh: 14.99, priceMaxLakh: 26.99,
    mileageKmpl: 14.87, engineCc: 1997, powerBhp: 197.0, torqueNm: 380,
    seating: 5, safetyStars: 5, bootLitres: 570, groundClearanceMm: 200,
    pros: JSON.stringify(['5-star NCAP', '200 bhp — most powerful in class', 'ADAS level 2 features']),
    cons: JSON.stringify(['Long waiting periods', 'ADAS can be finicky', 'Expensive top trims']),
    bestFor: 'Power + safety family SUV, tech enthusiasts, ADAS seekers',
  },
  {
    make: 'MG', model: 'Hector', variant: 'Sharp Pro Petrol AT',
    bodyType: 'suv', fuelType: 'petrol', transmission: 'automatic',
    priceMinLakh: 14.49, priceMaxLakh: 21.29,
    mileageKmpl: 14.89, engineCc: 1451, powerBhp: 141.0, torqueNm: 250,
    seating: 5, safetyStars: null, bootLitres: 587, groundClearanceMm: 200,
    pros: JSON.stringify(['Largest 14-inch touchscreen', 'Biggest boot in class', 'Feature-packed']),
    cons: JSON.stringify(['No NCAP rating', 'Average reliability record', 'Gimmicky features']),
    bestFor: 'Tech & feature seekers, big touchscreen priority',
  },
  {
    make: 'Tata', model: 'Harrier', variant: 'XZ+ AT',
    bodyType: 'suv', fuelType: 'diesel', transmission: 'automatic',
    priceMinLakh: 15.49, priceMaxLakh: 24.99,
    mileageKmpl: 16.35, engineCc: 1956, powerBhp: 168.0, torqueNm: 350,
    seating: 5, safetyStars: 5, bootLitres: 425, groundClearanceMm: 205,
    pros: JSON.stringify(['5-star NCAP', 'Best diesel torque in class', 'Muscular Land Rover DNA styling']),
    cons: JSON.stringify(['Diesel only', 'Expensive', 'No 7-seater option']),
    bestFor: 'Diesel power lovers, 5-seater SUV with muscle, highway touring',
  },
  {
    make: 'Tata', model: 'Safari', variant: 'XZ+ AT',
    bodyType: 'muv', fuelType: 'diesel', transmission: 'automatic',
    priceMinLakh: 16.49, priceMaxLakh: 26.99,
    mileageKmpl: 16.11, engineCc: 1956, powerBhp: 168.0, torqueNm: 350,
    seating: 7, safetyStars: 5, bootLitres: 73, groundClearanceMm: 205,
    pros: JSON.stringify(['5-star NCAP 7-seater', 'Commanding road presence', 'Panoramic sunroof']),
    cons: JSON.stringify(['Third row cramped for adults', 'Diesel only', 'Heavy and wide for city']),
    bestFor: '7-seater family, safety-focused, highway use',
  },
  {
    make: 'Hyundai', model: 'Alcazar', variant: 'Platinum 6-seater AT',
    bodyType: 'muv', fuelType: 'petrol', transmission: 'automatic',
    priceMinLakh: 16.99, priceMaxLakh: 21.06,
    mileageKmpl: 14.5, engineCc: 1997, powerBhp: 157.0, torqueNm: 191,
    seating: 6, safetyStars: null, bootLitres: 180, groundClearanceMm: 200,
    pros: JSON.stringify(['Captain seats in second row', 'Powerful petrol', 'Premium Hyundai features']),
    cons: JSON.stringify(['Expensive', 'No NCAP rating', 'Small third row']),
    bestFor: 'Premium 6-seater families, captain seat comfort priority',
  },
  {
    make: 'Jeep', model: 'Compass', variant: 'Model S Plus AT',
    bodyType: 'suv', fuelType: 'petrol', transmission: 'automatic',
    priceMinLakh: 22.99, priceMaxLakh: 29.99,
    mileageKmpl: 14.51, engineCc: 1368, powerBhp: 128.0, torqueNm: 270,
    seating: 5, safetyStars: null, bootLitres: 438, groundClearanceMm: 205,
    pros: JSON.stringify(['International brand prestige', 'Premium interiors', 'Capable on rough roads']),
    cons: JSON.stringify(['Very expensive', 'Limited service network', 'Low mileage']),
    bestFor: 'Premium/aspirational SUV buyers, Jeep brand enthusiasts',
  },
  {
    make: 'Mahindra', model: 'Scorpio N', variant: 'Z8 AT 4WD',
    bodyType: 'suv', fuelType: 'diesel', transmission: 'automatic',
    priceMinLakh: 14.99, priceMaxLakh: 24.49,
    mileageKmpl: 14.88, engineCc: 2184, powerBhp: 173.0, torqueNm: 400,
    seating: 7, safetyStars: null, bootLitres: 120, groundClearanceMm: 220,
    pros: JSON.stringify(['4WD off-road capability', 'Massive 400Nm torque', 'Commanding SUV presence']),
    cons: JSON.stringify(['Rough city ride', 'No NCAP rating', 'Heavy fuel consumption off-highway']),
    bestFor: 'Off-road enthusiasts, highway/rural road users, macho SUV buyers',
  },

  // ─── MPV / MUV (6) ──────────────────────────────────────────────────────────
  {
    make: 'Maruti Suzuki', model: 'Ertiga', variant: 'ZXI+ AT',
    bodyType: 'muv', fuelType: 'petrol', transmission: 'automatic',
    priceMinLakh: 8.69, priceMaxLakh: 13.32,
    mileageKmpl: 20.3, engineCc: 1462, powerBhp: 103.0, torqueNm: 137,
    seating: 7, safetyStars: null, bootLitres: 135, groundClearanceMm: 185,
    pros: JSON.stringify(['Best mileage 7-seater', 'Affordable price', 'Maruti service network']),
    cons: JSON.stringify(['No NCAP rating', 'Third row only for kids', 'Plain cabin']),
    bestFor: 'Budget 7-seater families, school run vehicles',
  },
  {
    make: 'Kia', model: 'Carens', variant: 'Prestige Plus 7-seater AT',
    bodyType: 'muv', fuelType: 'petrol', transmission: 'automatic',
    priceMinLakh: 10.52, priceMaxLakh: 19.79,
    mileageKmpl: 16.5, engineCc: 1497, powerBhp: 158.0, torqueNm: 253,
    seating: 7, safetyStars: null, bootLitres: 148, groundClearanceMm: 195,
    pros: JSON.stringify(['Most powerful 7-seater MPV', 'Premium Kia interiors', 'Comfortable 3 rows']),
    cons: JSON.stringify(['Expensive', 'No NCAP rating', 'Boot small with 3rd row up']),
    bestFor: 'Premium family MPV, long-distance family road trips',
  },
  {
    make: 'Toyota', model: 'Innova Crysta', variant: '2.4 GX MT',
    bodyType: 'muv', fuelType: 'diesel', transmission: 'manual',
    priceMinLakh: 19.99, priceMaxLakh: 26.76,
    mileageKmpl: 15.1, engineCc: 2393, powerBhp: 148.0, torqueNm: 343,
    seating: 7, safetyStars: null, bootLitres: 300, groundClearanceMm: 178,
    pros: JSON.stringify(['Legendary reliability', 'Torquey diesel', 'Most trusted family van in India']),
    cons: JSON.stringify(['Expensive', 'Dated interiors', 'Diesel only']),
    bestFor: 'Large families needing reliability, long road trips, business travel',
  },
  {
    make: 'Toyota', model: 'Innova HyCross', variant: 'VX Hybrid',
    bodyType: 'muv', fuelType: 'hybrid', transmission: 'automatic',
    priceMinLakh: 19.77, priceMaxLakh: 28.97,
    mileageKmpl: 21.1, engineCc: 1987, powerBhp: 183.0, torqueNm: 206,
    seating: 7, safetyStars: null, bootLitres: 300, groundClearanceMm: 185,
    pros: JSON.stringify(['Hybrid MPV — best fuel efficiency in class', 'Premium monocoque ride', 'ADAS features']),
    cons: JSON.stringify(['Very expensive', 'No diesel option', 'Hybrid battery long-term concern']),
    bestFor: 'Premium family transport, corporate travel, eco-focused large families',
  },
  {
    make: 'Maruti Suzuki', model: 'XL6', variant: 'Alpha Plus AT',
    bodyType: 'muv', fuelType: 'petrol', transmission: 'automatic',
    priceMinLakh: 11.96, priceMaxLakh: 14.54,
    mileageKmpl: 20.27, engineCc: 1462, powerBhp: 103.0, torqueNm: 137,
    seating: 6, safetyStars: null, bootLitres: 209, groundClearanceMm: 180,
    pros: JSON.stringify(['Captain seats in middle row', 'Good mileage for 6-seater', 'Affordable premium MPV']),
    cons: JSON.stringify(['No NCAP rating', 'Underpowered', 'Third row tight']),
    bestFor: 'Captain seat comfort on a budget, small 6-member families',
  },
  {
    make: 'Mahindra', model: 'Marazzo', variant: 'M8',
    bodyType: 'muv', fuelType: 'diesel', transmission: 'manual',
    priceMinLakh: 14.99, priceMaxLakh: 17.60,
    mileageKmpl: 17.0, engineCc: 1497, powerBhp: 121.0, torqueNm: 300,
    seating: 8, bootLitres: 120, groundClearanceMm: 180,
    pros: JSON.stringify(['8-seater capacity', 'Shark-inspired aerodynamics', 'Quiet diesel']),
    cons: JSON.stringify(['Underpowered for size', 'Plain interiors', 'No petrol option']),
    bestFor: 'Large 8-member families, outstation travel groups',
  },

  // ─── Electric (4) ───────────────────────────────────────────────────────────
  {
    make: 'Tata', model: 'Nexon EV', variant: 'Max LR',
    bodyType: 'electric', fuelType: 'electric', transmission: 'automatic',
    priceMinLakh: 14.79, priceMaxLakh: 19.99,
    mileageKmpl: null, engineCc: null, powerBhp: 143.0, torqueNm: 250,
    seating: 5, safetyStars: 5, bootLitres: 350, groundClearanceMm: 209,
    pros: JSON.stringify(['5-star NCAP', '465 km certified range', 'Best-selling EV in India']),
    cons: JSON.stringify(['Home charging needs 15-amp socket', 'Real-world range ~350 km', 'AC reduces range']),
    bestFor: 'Home-charging EV adopters, 5-star safety seekers, city + occasional highway',
  },
  {
    make: 'Tata', model: 'Tiago EV', variant: 'Long Range XZ+',
    bodyType: 'electric', fuelType: 'electric', transmission: 'automatic',
    priceMinLakh: 8.69, priceMaxLakh: 11.99,
    mileageKmpl: null, engineCc: null, powerBhp: 74.0, torqueNm: 114,
    seating: 5, safetyStars: 4, bootLitres: 242, groundClearanceMm: 165,
    pros: JSON.stringify(['Most affordable EV in India', '315 km certified range', 'Ideal city EV']),
    cons: JSON.stringify(['Slow highway speeds', 'Small boot', 'Limited fast chargers']),
    bestFor: 'First-time EV buyers, city-only drivers, budget EV segment',
  },
  {
    make: 'MG', model: 'ZS EV', variant: 'Excite Plus',
    bodyType: 'electric', fuelType: 'electric', transmission: 'automatic',
    priceMinLakh: 18.98, priceMaxLakh: 25.00,
    mileageKmpl: null, engineCc: null, powerBhp: 174.0, torqueNm: 280,
    seating: 5, safetyStars: null, bootLitres: 448, groundClearanceMm: 177,
    pros: JSON.stringify(['461 km certified range', 'Large boot for an EV', 'Premium features']),
    cons: JSON.stringify(['Expensive', 'MG service network smaller', 'No NCAP rating']),
    bestFor: 'Premium EV buyers, range anxiety concerns, MG tech enthusiasts',
  },
  {
    make: 'BYD', model: 'Atto 3', variant: 'Standard',
    bodyType: 'electric', fuelType: 'electric', transmission: 'automatic',
    priceMinLakh: 24.99, priceMaxLakh: 33.99,
    mileageKmpl: null, engineCc: null, powerBhp: 201.0, torqueNm: 310,
    seating: 5, safetyStars: 5, bootLitres: 440, groundClearanceMm: 175,
    pros: JSON.stringify(['5-star NCAP', '521 km certified range', 'Blade battery technology safest']),
    cons: JSON.stringify(['Very expensive', 'BYD service network tiny', 'Brand unfamiliar in India']),
    bestFor: 'Premium EV early adopters, max range requirement, safety-first EV buyers',
  },

  // ─── Luxury / Premium (2) ────────────────────────────────────────────────────
  {
    make: 'Toyota', model: 'Fortuner', variant: 'Legender 4x2 AT',
    bodyType: 'luxury', fuelType: 'diesel', transmission: 'automatic',
    priceMinLakh: 33.43, priceMaxLakh: 51.44,
    mileageKmpl: 14.0, engineCc: 2755, powerBhp: 201.0, torqueNm: 500,
    seating: 7, safetyStars: null, bootLitres: 200, groundClearanceMm: 225,
    pros: JSON.stringify(['500 Nm torque king', 'Legendary Toyota reliability', 'Dominant road presence']),
    cons: JSON.stringify(['Very expensive', 'Rides rough in city', 'Fuel thirsty']),
    bestFor: 'Aspirational premium SUV, rural + highway flagship, status symbol',
  },
  {
    make: 'Ford', model: 'Endeavour', variant: 'Titanium Plus 4x4 AT',
    bodyType: 'luxury', fuelType: 'diesel', transmission: 'automatic',
    priceMinLakh: 37.99, priceMaxLakh: 44.99,
    mileageKmpl: 12.0, engineCc: 1996, powerBhp: 167.0, torqueNm: 420,
    seating: 7, safetyStars: 5, bootLitres: 220, groundClearanceMm: 225,
    pros: JSON.stringify(['5-star NCAP', '4x4 terrain management', 'Plush interiors']),
    cons: JSON.stringify(['Ford India discontinued — parts concern', 'Expensive', 'Low mileage']),
    bestFor: 'Pre-owned premium 4x4 buyers, off-road luxury seekers',
  },
]

async function main() {
  console.log('🌱  Clearing existing data...')
  await prisma.shortlistItem.deleteMany()
  await prisma.message.deleteMany()
  await prisma.session.deleteMany()
  await prisma.car.deleteMany()

  console.log(`🚗  Seeding ${cars.length} cars...`)
  await prisma.car.createMany({ data: cars })

  const count = await prisma.car.count()
  console.log(`✅  Seeded ${count} cars successfully.`)
}

main()
  .catch((err) => {
    console.error('Seed failed:', err)
    process.exit(1)
  })
  .finally(() => prisma.$disconnect())
